primeUtils: 
  modulePath: ./prime.cpp
  exports:
    sieveOfErathos: 
      snippetName: lib/sieveOfErathos 
      functions: 
        - sieveOfErathos 
    primeFactorize:
      snippetName: lib/primeFactorize
      functions: 
        - primeFactorize
